version: "3.0"

services:

  email-reader:
      container_name: email-reader
      restart: on-failure
      build: ./
      networks: [backend-services]
      volumes:
      - ./attachments:/attachments
      expose:
        - "8081"
      ports:
        - 8081:8080
      environment:
        WAIT_HOSTS: mysql:3306
        SPRING_DATASOURCE_URL: jdbc:mysql://er-mysql:3306/emailreader?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
        SPRING_ACTIVEMQ_BROKER-URL: tcp://er-activemq:61616
      depends_on:
        - er-mysql
        - er-activemq

  er-activemq:
    container_name: er-activemq
    image: webcenter/activemq:latest
    ports:
      # mqtt
      - "1884:1883"
      # amqp
      - "5673:5672"
      # ui
      - "8161:8161"
      # stomp
      - "61613:61613"
      # ws
      - "61614:61614"
      # jms
      - "61616:61616"
    networks: [backend-services]
    volumes: ["activemq-data:/opt/activemq/conf", "activemq-data:/data/activemq", "activemq-data:/var/log/activemq"]
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://localhost:8161/admin"]
      interval: 5s
      timeout: 3s
      retries: 20
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: password
      ACTIVEMQ_WRITE_LOGIN: write
      ACTIVEMQ_WRITE_PASSWORD: password
      ACTIVEMQ_READ_LOGIN: read
      ACTIVEMQ_READ_PASSWORD: password
      ACTIVEMQ_JMX_LOGIN: jmx
      ACTIVEMQ_JMX_PASSWORD: password
      ACTIVEMQ_STATIC_TOPICS: static-topic-1;static-topic-2
      ACTIVEMQ_STATIC_QUEUES: static-queue-1;static-queue-2
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048

  er-mysql:
    restart: always
    container_name: er-mysql
    image: mysql
    # command: --default-authentication-plugin=mysql_native_password
    networks: [backend-services]
    environment:
      MYSQL_DATABASE: emailreader
      MYSQL_ROOT_PASSWORD: "Temp@12345"
      # MYSQL_ROOT_HOST: "%"
      MYSQL_USER: admin
      MYSQL_PASSWORD: "bourntec@12"
    volumes:
      # - ./sql:/docker-entrypoint-initdb.d
      - ./sql:/var/lib/mysql
    ports:
      - "3308:3306"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    healthcheck:
      test: "/usr/bin/mysql --user=root --password='Temp@12345'--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  er-newman:
    restart: always
    container_name: er-newman
    image: postman/newman
    command: run https://www.getpostman.com/collections/3982ace13976ed8874bc
    networks: [backend-services]
    volumes:
      - ./newman:/etc/newman
  
  er-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: er-elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic


volumes:
  activemq-data: {}
  sql: {}
  newman: {}
  esdata: {}

networks:
  backend-services:
    driver: bridge
  elastic:
    driver: bridge

